export const ADD_SHIFT = 'ADD_SHIFT';
export const REMOVE_SHIFT = 'REMOVE_SHIFT';
export const SAVE_TEMP_SHIFTS = 'SAVE_TEMP_SHIFTS';
export const SYNCHRONIZE_ARRAYS = 'SYNCHRONIZE_ARRAYS';
export const RESET_CHANGES = 'RESET_CHANGES';
export const SET_AUTH = 'SET_AUTH';
export const FETCH_EMPLOYEES = 'FETCH_EMPLOYEES';
export const SAVE_EMPLOYEES = 'SAVE_EMPLOYEES';
